controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
api_get_posts:
  path: /posts
  controller: App\Controller\PostsController::getPosts
  methods: GET
